# k-Means clustering

### Importing Libraries

In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("C:/Users/SN132/Desktop/down.jpeg")

# RGB Conversion

In [3]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# RESHAPE

In [4]:
vec=imgrgb.reshape((-1,3))
vec

array([[60, 88, 89],
       [59, 87, 88],
       [57, 85, 86],
       ...,
       [ 0, 31, 38],
       [ 0, 29, 36],
       [ 0, 30, 38]], dtype=uint8)

# Float Conversion

In [5]:
vec=np.float32(vec)
vec

array([[60., 88., 89.],
       [59., 87., 88.],
       [57., 85., 86.],
       ...,
       [ 0., 31., 38.],
       [ 0., 29., 36.],
       [ 0., 30., 38.]], dtype=float32)

# Iteration Termination Criteria

In [6]:
criteria =(cv2.TERM_CRITERIA_EPS+ cv2.TERM_CRITERIA_MAX_ITER,100,1)

# CLUSTER Condition

In [7]:
k = 3
attempts = 100

# K-Means Cluster

In [8]:
cmpactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[ 16.56177 ,  33.819736,  40.44013 ],
       [193.29396 , 201.69734 , 188.15768 ],
       [ 84.02139 , 115.72763 , 114.29635 ]], dtype=float32)

# UINT Convertion

In [9]:
center = np.uint8(center)
center

array([[ 16,  33,  40],
       [193, 201, 188],
       [ 84, 115, 114]], dtype=uint8)

# Flattening and Reshape

In [10]:
res = center[label.flatten()]
res_img = res.reshape((imgrgb.shape))
res_img

array([[[ 84, 115, 114],
        [ 84, 115, 114],
        [ 84, 115, 114],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]],

       [[ 84, 115, 114],
        [ 84, 115, 114],
        [ 84, 115, 114],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]],

       [[ 84, 115, 114],
        [ 84, 115, 114],
        [ 84, 115, 114],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]],

       ...,

       [[ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]],

       [[ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]],

       [[ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40],
        ...,
        [ 16,  33,  40],
        [ 16,  33,  40],
        [ 16,  33,  40]]

# IMAGE PROCESSING

In [11]:
cv2.imshow("img",img)
cv2.imshow("segmented",res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# MEAN SHIFT

In [12]:
img=cv2.imread("C:/Users/SN132/Desktop/down.jpeg")
segmented_image = cv2.pyrMeanShiftFiltering(img,40,40)
cv2.imshow("img",img)
cv2.imshow("segmented_image",segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()